# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    subscriptionId: '23b7dac6-cdf3-4feb-814f-1a76c48fe1c5'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'prd-wppcs-inf-core'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'active-directory-new-domain-ha-2-dc/azuredeploy.json'
    overrideParameters: '-projectName "Core infrastructure" -linkedTemplateUri https://raw.githubusercontent.com/jimmellor/wppcloudstudio-core-inf/master/active-directory-new-domain-ha-2-dc/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Deployment Pipeline Template'