# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '23b7dac6-cdf3-4feb-814f-1a76c48fe1c5'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    # csmFile: 'active-directory-new-domain-ha-2-dc/azuredeploy.json'
    csmFileLink: 'https://raw.githubusercontent.com/jimmellor/wppcloudstudio-core-inf/master/active-directory-new-domain-ha-2-dc/azuredeploy.json?token=AABRDGFX42YKZFR63FPISXK62DAIE'
    csmParametersFileLink: 'https://raw.githubusercontent.com/jimmellor/wppcloudstudio-core-inf/master/active-directory-new-domain-ha-2-dc/azuredeploy.parameters.json?token=AABRDGDLAJ4XL3VQ2IAYYY262DAKA'
    # csmParametersFile: 'active-directory-new-domain-ha-2-dc/azuredeploy.parameters.json'
    overrideParameters: '-adminUsername hznadmin -adminPassword Emily1001 -domainName wppcloud.studio -location uksouth -dnsPrefix wppcloudstudio'
    deploymentMode: 'Incremental'